/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ALL_MENU_ITEMS: typeof import('./src/constants/index').ALL_MENU_ITEMS
  const Activity: typeof import('react').Activity
  const BADGE_STYLES: typeof import('./src/constants/index').BADGE_STYLES
  const BASE_BTN: typeof import('./src/constants/index').BASE_BTN
  const CARD: typeof import('./src/constants/index').CARD
  const CATEGORIES: typeof import('./src/constants/index').CATEGORIES
  const DELIVERY_PAYMENT: typeof import('./src/constants/index').DELIVERY_PAYMENT
  const EMOJIS: typeof import('./src/constants/index').EMOJIS
  const FEATURES: typeof import('./src/constants/index').FEATURES
  const FLOATING_EMOJIS: typeof import('./src/constants/index').FLOATING_EMOJIS
  const FOOTER_CONTACT: typeof import('./src/constants/index').FOOTER_CONTACT
  const FOOTER_MENU: typeof import('./src/constants/index').FOOTER_MENU
  const FOOTER_SVC: typeof import('./src/constants/index').FOOTER_SVC
  const Fragment: typeof import('react').Fragment
  const GALLERY_SLIDES: typeof import('./src/constants/index').GALLERY_SLIDES
  const GLASS_STYLE: typeof import('./src/constants/index').GLASS_STYLE
  const GRADIENTS: typeof import('./src/constants/index').GRADIENTS
  const HERO_TAGS: typeof import('./src/constants/index').HERO_TAGS
  const HOME_MENU_ITEMS: typeof import('./src/constants/index').HOME_MENU_ITEMS
  const INFO_ROWS: typeof import('./src/constants/index').INFO_ROWS
  const INJECTED_CSS: typeof import('./src/constants/index').INJECTED_CSS
  const LABEL_CLS: typeof import('./src/constants/index').LABEL_CLS
  const NAV_LINKS: typeof import('./src/constants/index').NAV_LINKS
  const PAYMENT_METHODS: typeof import('./src/constants/index').PAYMENT_METHODS
  const PROMO_CODES: typeof import('./src/constants/index').PROMO_CODES
  const REVIEWS: typeof import('./src/constants/index').REVIEWS
  const SEATING_OPTIONS: typeof import('./src/constants/index').SEATING_OPTIONS
  const SHIPPING_METHODS: typeof import('./src/constants/index').SHIPPING_METHODS
  const SIZES: typeof import('./src/constants/index').SIZES
  const SOCIALS: typeof import('./src/constants/index').SOCIALS
  const STATS: typeof import('./src/constants/index').STATS
  const STEP_LABELS: typeof import('./src/constants/index').STEP_LABELS
  const Suspense: typeof import('react').Suspense
  const TECH_STACK: typeof import('./src/constants/index').TECH_STACK
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const formatDate: typeof import('./src/utils/format.js').formatDate
  const formatRp: typeof import('./src/utils/helpers').formatRp
  const formatRupiah: typeof import('./src/utils/format.js').formatRupiah
  const formatTime: typeof import('./src/utils/format.js').formatTime
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const loadMidtransSnap: typeof import('./src/utils/midtrans.js').loadMidtransSnap
  const mapMenuFromApi: typeof import('./src/utils/helpers').mapMenuFromApi
  const memo: typeof import('react').memo
  const openSnapPayment: typeof import('./src/utils/midtrans.js').openSnapPayment
  const parsePrice: typeof import('./src/utils/helpers').parsePrice
  const seatingLabel: typeof import('./src/utils/format.js').seatingLabel
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useOptimistic: typeof import('react').useOptimistic
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { BtnSize, BadgeColor, Page, FloatingEmoji, MenuItemData } from './src/types/index'
  import('./src/types/index')
}
